export const  PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_LOAD_SUCCESS = 'PRODUCT_LOAD_SUCCESS';
export const  PRODUCT_LOAD_ERROR = 'PRODUCT_LOAD_ERROR';
export const SEARCH_VALUE = 'SEARCH_VALUE';
export const SAVE_SEARCH = 'SAVE_SEARCH';
